apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: helm-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["*"]

- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["*"]

