apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: jenkins
roleRef:
  kind: Role
  name: helm-role
  apiGroup: rbac.authorization.k8s.io

